import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

const source = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8")

describe("layout source contracts", () => {
  it("keeps connection details scrollable with fixed dialog chrome", () => {
    const css = source("../src/styles.css")
    const app = source("../src/App.tsx")
    expect(css).toContain("max-height: calc(100dvh - 36px)")
    expect(css).toContain(".connection-dialog-body { min-height: 0; overflow-y: auto; }")
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto")
    expect(app).toContain('className="connection-dialog-body"')
  })

  it("keeps tabs mobile-scrollable and exposes the subagent tab contract", () => {
    const css = source("../src/styles.css")
    const app = source("../src/App.tsx")
    expect(css).toContain(".tabs { height: 46px; flex: 0 0 auto; display: flex; gap: 6px; overflow-x: auto")
    expect(app).toContain("const visibleSubagentEntries = useMemo(() => visibleSubagents(subagents), [subagents])")
    expect(app).toContain("Subagents <span>{visibleSubagentEntries.length}</span>")
    expect(app).toContain("<SubagentActivity subagents={visibleSubagentEntries}")
    expect(app).toContain("if (group) group.push(session)")
    expect(app).toContain("messageRefreshGenerationRef")
    expect(app).toContain("todosRefreshGenerationRef")
    expect(app).toContain("const selectTab")
    expect(app).toContain("followOutputRef.current = true")
    expect(app).toContain("lastScrollTopRef.current = detailContentRef.current.scrollTop")
    expect((app.match(/lastScrollTopRef\.current = detailContentRef\.current\.scrollTop/g) ?? [])).toHaveLength(2)
  })

  it("hides the composer and root working strip for subagent activity while restoring output follow on Activity", () => {
    const app = source("../src/App.tsx")
    expect(app).toContain('const showComposer = tab !== "subagents"')
    expect(app).toContain("{showComposer && (session.status === \"busy\" || session.status === \"retry\")")
    expect(app).toContain('{showComposer && <form className="composer" onSubmit={submit}>')
    expect(app).toContain('if (next === "activity")')
    expect(app).toContain("detailContentRef.current.scrollTop = detailContentRef.current.scrollHeight")
  })

  it("keeps Subagents scrolling within its fixed-height detail region", () => {
    const css = source("../src/styles.css")
    const app = source("../src/App.tsx")
    const subagents = source("../src/SubagentActivity.tsx")
    expect(app).toContain('className={`detail-content ${tab === "subagents" ? "subagent-content" : ""}`}')
    expect(app).toContain('className={`input-dock ${tab === "subagents" ? "subagent-dock" : ""}`}')
    expect(subagents).toContain('className="subagent-messages"')
    expect(css).toContain(".detail-header { min-height: 86px; flex: 0 0 auto;")
    expect(css).toContain(".tabs { height: 46px; flex: 0 0 auto;")
    expect(css).toContain(".detail-content.subagent-content { min-height: 0; overflow: hidden; }")
    expect(css).toContain(".input-dock.subagent-dock { min-height: 0; max-height: min(52dvh, max(0px, calc(100dvh - 64px - env(safe-area-inset-top) - 86px - 46px - 160px))); overflow-x: hidden; overflow-y: auto; overscroll-behavior: contain; }")
    expect(css).toContain(".input-dock.subagent-dock { max-height: min(52dvh, max(0px, calc(100dvh - 56px - env(safe-area-inset-top) - 76px - 46px - 132px - 112px))); }")
    expect(css).toContain(".subagent-dock .permission-panel, .subagent-dock .question-panel { max-height: none; }")
    expect(css).toContain(".subagent-dock .permission-panel, .subagent-dock .question-panel:not(.collapsed) { overflow: visible; }")
    expect(css).toContain(".subagent-view { height: 100%; min-height: 0; display: grid; grid-template-columns: minmax(190px, 280px) minmax(0, 1fr); grid-template-rows: minmax(0, 1fr); }")
    expect(css).toContain(".subagent-list, .subagent-messages { min-height: 0; overflow-y: auto; }")
    expect(css).toContain(".subagent-messages > .message-list { width: 100%; min-width: 0; overflow: visible; }")
    expect(css).toContain("@media (max-width: 640px) { .subagent-view { grid-template-columns: 1fr; grid-template-rows: auto minmax(0, 1fr); }")
    expect(css).toContain(".subagent-list { max-height: 132px; border-right: 0; border-bottom: 1px solid var(--line); }")
  })

  it("keeps progress draining bounded by a timeout", () => {
    const relay = source("../src/useRelay.ts")
    expect(relay).toContain("Message progress timed out.")
    expect(relay).toContain("verifiedMessageIds")
  })

  it("uses exact, modal-only connection timing and preserves zero-millisecond RTT", () => {
    const app = source("../src/App.tsx")
    const relay = source("../src/useRelay.ts")
    expect(app).toContain("exactConnectionTime(health.lastContact, now)")
    expect(app).toContain("exactConnectionTime(relayState.lastSyncedAt, now)")
    expect(app).toContain('health?.rtt !== undefined ? `${health.rtt} ms`')
    expect(app).toContain("window.setInterval(() => setNow(Date.now()), 1_000)")
    expect(relay).toContain("Connection handshake timed out.")
    expect(relay).toContain("HANDSHAKE_TIMEOUT_MS")
    expect(relay).toContain("shouldReconnectTransportOnResume")
    expect(relay).toContain("const retireTransport = useCallback")
    expect(relay).toContain('retireTransport("Connection interrupted")')
    expect(relay).toContain("pending.generation !== generation")
    expect(relay).toContain("setError((current) => current === \"Connection handshake timed out.\"")
    expect(relay).toContain("socket?.readyState === WebSocket.CONNECTING")
    expect(relay).toContain("shouldReconnectTransportOnResume")
  })
})
