import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"
import { cacheNamespace } from "../src/features/relay/relayModel"

const source = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8")

describe("layout source contracts", () => {
  it("contains the folder overflow overlay within its neutral row without masking pills or intercepting input", () => {
    const css = source("../src/styles.css")
    expect(css).toMatch(/\.folder-filters-row \{[^}]*position: relative;[^}]*background: var\(--surface\);/)
    const overlay = css.match(/\.folder-filters-row\[data-overflow-right="true"\]::after \{([^}]*)\}/)?.[1]
    expect(overlay).toContain("inset: 4px 0 12px auto;")
    expect(overlay).toContain("linear-gradient(to right, transparent, var(--surface))")
    expect(overlay).toContain("pointer-events: none;")
    expect(overlay).not.toContain("mask")
    expect(css).not.toMatch(/\.folder-filters[^{}]*(?:hover|focus)/)
    expect(css).toMatch(/\.folder-filters \.folder-filter \{[^}]*min-height: 44px;/)
  })
  it("keeps metadata on one line with shrinkable branch text and delivery at the right", () => {
    const css = source("../src/styles.css")
    expect(css).toMatch(/\.session-header-pill \{[^}]*grid-template-columns: auto minmax\(0, 1fr\);/)
    expect(css).toMatch(/\.session-location \{[^}]*flex-wrap: nowrap;/)
    expect(css).toContain(".session-location .session-branch { flex: 0 1 auto; }")
    expect(css).toMatch(/\.session-location \{[^}]*justify-content: flex-end;/)
    expect(css).toContain(".session-location > span > span { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }")
    expect(css).toContain(".delivery-flag { margin-left: auto; }")
  })
  it("keeps Subagents opaque through the measured cards and fades across the shadow gutter while Activity fades continuously", () => {
    const css = source("../src/styles.css")
    const tokens = source("../public/design-tokens.css")
    expect(css).toContain("12px 8px; border: 0; background: transparent;")
    expect(css).toMatch(/\.session-detail::before \{[^}]*top: 0;[^}]*z-index: 1;[^}]*pointer-events: none;/)
    expect(css).toContain("height: calc(var(--session-header-height, 0px) + var(--subagent-selector-height, 0px) + var(--session-header-coverage) + var(--session-header-fade-size))")
    expect(tokens).toContain("--session-header-coverage: 12px")
    expect(css).toContain("background: var(--session-header-fade)")
    expect(css).not.toContain("header-status-pulse")
    expect(css).not.toContain("--header-tint")
    expect(tokens).not.toMatch(/--session-header-(busy|idle|attention|retry|error):/)
    expect(tokens).toContain("var(--background) calc(100% - var(--session-header-fade-size)), transparent 100%")
    expect(css).toMatch(/\.subagent-list \{[^}]*padding: 12px 12px 24px;[^}]*\}/)
    expect(css).toMatch(/\.subagent-list \{[^}]*overflow-x: auto;[^}]*scrollbar-width: none;/)
    expect(css).toContain(".subagent-list::-webkit-scrollbar { display: none; }")
    expect(css).toMatch(/\.subagent-selector \{[^}]*top: 0;[^}]*padding-top: env\(safe-area-inset-top\);/)
    expect(css).toContain('.session-detail[data-tab="activity"] { --session-header-fade: var(--activity-header-fade); --session-header-fade-size: var(--activity-header-fade-size); }')
    expect(css).toContain('.session-detail[data-tab="subagents"] { --session-header-fade-size: var(--subagent-header-fade-size); }')
    expect(css).toContain('.session-detail[data-tab="subagents"]::before { height: calc(var(--subagent-selector-height, 0px) - 24px + var(--session-header-fade-size)); background: linear-gradient(to bottom, var(--background) 0, var(--background) calc(100% - var(--session-header-fade-size)), transparent 100%); }')
    expect(css).not.toContain('.session-detail:is([data-tab="activity"], [data-tab="subagents"])')
    expect(tokens).toContain('--session-header-fade-size: 28px')
    expect(css.match(/\.subagent-list \{[^}]*\}/)?.[0]).not.toContain("border-bottom")
  })
  it("keeps connection details scrollable with fixed dialog chrome", () => {
    const css = source("../src/styles.css")
    const connectionDetails = source("../src/features/workspace/ConnectionDetails.tsx")
    expect(css).toContain("max-height: calc(100dvh - 36px)")
    expect(css).toContain(".connection-dialog-body { min-height: 0; overflow-y: auto; }")
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto")
    expect(connectionDetails).toContain('className="connection-dialog-body"')
  })

  it("overlays the header from the pane top with scrolling initial padding and no lower mask", () => {
    const css = source("../src/styles.css")
    expect(css).toContain('.detail-header { position: absolute; top: 0; left: 0; right: 0; z-index: 3; pointer-events: none;')
    expect(css).toMatch(/\.session-header-pill \{ max-width: 780px; margin-inline: auto; pointer-events: auto;/)
    expect(css).toContain('.detail-content:not(.subagent-content)::before { content: ""; display: block; height: var(--session-header-height, 0px); }')
    expect(css).toContain('.subagent-message-scroll::before { content: ""; display: block; height: calc(var(--session-header-height, 0px) + var(--subagent-selector-height, 0px)); }')
    for (const rule of css.replace(/\/\*[\s\S]*?\*\//g, "").matchAll(/([^{}]+)\{([^{}]*mask-image:[^{}]*)\}/g)) {
      expect(rule[1]!.trim()).toBe('.subagent-selector[data-overflow-right="true"]::after')
    }
  })

  it("places semantic tabs below the composer in the inbox and conversation layout", () => {
    const css = source("../src/styles.css")
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    const tabs = source("../src/components/ui/Tabs.tsx")
    const activityScroll = source("../src/features/session/hooks/useActivityScroll.ts")
    expect(css).toContain('grid-template-areas: "content";')
    expect(css).toMatch(/\.session-dock \{ position: absolute;[^}]*pointer-events: none;/)
    expect(css).toContain('.session-dock > :not(.command-bar), .command-bar > * { pointer-events: auto; }')
    expect(css).toContain('background: linear-gradient(to top, var(--background), transparent)')
    expect(css).toContain('.detail-content:not(.subagent-content)::after, .subagent-message-scroll::after { content: ""; display: block; height: var(--session-dock-height, 0px);')
    expect(sessionDetail).toContain('ref={dockOverlay.ref} className="session-dock"')
    expect(sessionDetail).toContain('headerOverlay.height, dockOverlay.height]')
    expect(css).not.toContain('"heading tools"')
    expect(css).toContain(".session-tools .tabs button { flex: 1 1 0; min-width: 0;")
    expect(sessionDetail).toContain('orientation="horizontal"')
    expect(workspace).toContain('aria-label="Workspace navigator"')
    expect(workspace).toContain('>New session</Button>')
    expect(workspace).toContain('className="inbox-utilities"')
    expect(sessionDetail).toContain('{session.additions} additions . {session.deletions} deletions')
    expect(workspace).not.toContain('className="session-legend"')
    expect(sessionDetail).toContain("const visibleSubagentEntries = useMemo(() => visibleSubagents(subagents), [subagents])")
    expect(sessionDetail).toContain("Subagents <span>{visibleSubagentEntries.length}</span>")
    expect(sessionDetail).toContain("<SubagentActivity subagents={visibleSubagentEntries}")
    expect(workspace).toContain("visibleSessions.map((session)")
    expect(workspace).not.toContain("collapsedGroups")
    expect(workspace).toContain('aria-label="Filter by folder"')
    expect(sessionDetail).toContain("messageRefreshGenerationRef")
    expect(sessionDetail).toContain("todosRefreshGenerationRef")
    expect(sessionDetail).toContain("const selectTab")
    expect(sessionDetail).toContain("<Tabs")
    expect(sessionDetail).toContain('role="tabpanel"')
    expect(activityScroll).toContain("const isNearActivityBottom")
    expect(activityScroll).toContain("const restorePendingRef = useRef(false)")
    expect(tabs).toContain('event.key === "ArrowRight"')
    expect(tabs).toContain('event.key === "Home"')
    expect(tabs).toContain('aria-controls=')
  })

  it("hides the composer and root working strip for subagent activity while preserving Activity follow intent", () => {
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    const activityScroll = source("../src/features/session/hooks/useActivityScroll.ts")
    const composer = source("../src/features/session/components/Composer.tsx")
    expect(sessionDetail).toContain('const showComposer = tab !== "subagents"')
    expect(sessionDetail).not.toContain('className="command-progress"')
    expect(sessionDetail).toContain("{showComposer && <Composer")
    expect(composer).toContain('<form className="composer" onSubmit=')
    expect(sessionDetail).toContain("activityScroll.beforeTabChange")
    expect(activityScroll).toContain("if (leavingActivity && contentRef.current)")
    expect(activityScroll).toContain("if (followOutputRef.current) {")
    expect(activityScroll).toContain("} else if (restorePendingRef.current) {")
    expect(activityScroll).toContain("element.scrollTop = scrollTopRef.current")
    expect(activityScroll).toContain("restorePendingRef.current = false")
    expect(activityScroll).not.toContain("document.activeElement")
    expect(sessionDetail).not.toContain("followOutputRef.current = true\n          const prepared = await prepareMessageProgress(partial)")
    expect(sessionDetail).toContain("const cache = applyPreparedMessageProgress(messageCacheRef.current, prepared)\n          await persistMessageCache(cache)")
    expect(activityScroll).toContain("followOutputRef.current = isNearActivityBottom(element)")
    expect(activityScroll).toContain("if (enteringActivity) restorePendingRef.current = true")
  })

  it("keeps Subagents scrolling within its fixed-height detail region", () => {
    const css = source("../src/styles.css")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    const subagents = source("../src/features/session/components/SubagentActivity.tsx")
    expect(sessionDetail).toContain('className={`detail-content ${tab === "subagents" ? "subagent-content" : ""}`}')
    expect(sessionDetail).toContain('dockHeight={dockOverlay.height}')
    expect(subagents).toContain('className="subagent-messages"')
    expect(subagents).toContain('className="subagent-message-scroll" ref={activityScroll.contentRef} onScroll={activityScroll.onScroll}')
    expect(subagents).toContain('useActivityScroll(true, [childKey, messages, loading, error, pending, showToolCalls, headerHeight, selectorOverlay.height, dockHeight])')
    expect(css).not.toContain('grid-area: heading')
    expect(css).toContain(".session-tools { min-width: 0; min-height: 0; }")
    expect(css).toContain(".detail-content.subagent-content { min-height: 0; overflow: hidden; }")
    expect(css).toContain(".request-stack { min-width: 0; min-height: 0; flex: 1 1 auto; overflow-x: hidden; overflow-y: auto;")
    expect(css).toContain('.request-stack > .permission-panel, .request-stack > .question-panel:not(.collapsed) { max-height: none; overflow: visible; }')
    expect(css).toContain(".subagent-view { position: relative; height: 100%; min-width: 0; min-height: 0; display: grid; grid-template-columns: minmax(0, 1fr); grid-template-rows: minmax(0, 1fr); }")
    expect(css).toContain(".subagent-list { min-width: 0; display: flex; flex-wrap: nowrap;")
    expect(css).toContain("overflow-x: auto; overflow-y: hidden;")
    expect(css).toContain("flex: 0 0 clamp(230px, 32vw, 300px)")
    expect(css).toContain("min-height: 96px")
    expect(css).toContain("-webkit-line-clamp: 2")
    expect(css).toContain(".subagent-list .subagent-pill.selected { color: var(--navigation-selected-text); background: var(--navigation-selected-surface);")
    expect(css).toContain(".subagent-status.error { color: var(--danger); background: var(--danger-surface); }")
    expect(css).toContain(".subagent-messages { min-height: 0; display: flex; flex-direction: column; overflow: hidden; }")
    expect(subagents).not.toContain('className="work-strip"')
    expect(css).toContain(".subagent-message-scroll { min-height: 0; flex: 1 1 auto; overflow-y: auto;")
    expect(css).toContain(".subagent-message-scroll > .message-list { width: 100%; min-width: 0; overflow: visible; }")
    expect(css).not.toContain(".subagent-list { max-height: 132px;")
  })

  it("bounds the full workspace and request dock without imposing an overlay-sized content minimum", () => {
    const css = source("../src/styles.css")
    expect(css).toMatch(/\.workspace-layout \{[^}]*grid-template-rows: minmax\(0, 1fr\);/)
    expect(css).toContain('.workspace-layout { grid-template-columns: minmax(0, 1fr); }')
    expect(css).toMatch(/\.detail-panel \{[^}]*min-height: 0;/)
    expect(css).toMatch(/\.session-detail \{[^}]*min-height: 0;[^}]*grid-template-rows: minmax\(0, 1fr\);/)
    expect(css).not.toContain('.app-shell { grid-template-rows:')
    expect(css).not.toMatch(/\.detail-content:not\(\.subagent-content\) \{[^}]*\spadding-top:/)
    expect(css).toContain('max-height: calc(100% - max(var(--session-header-height, 0px), var(--subagent-selector-height, 0px)) - 24px)')
    expect(css).toMatch(/\.session-dock > \* \{[^}]*max-width: 780px;[^}]*margin-inline: auto;/)
    expect(css).toContain('container: session-detail / size;')
    expect(css).toContain('@container session-detail (max-height: 380px)')
    expect(css).toContain('container: workspace-navigator / size;')
    expect(css).toContain('@container workspace-navigator (max-height: 380px)')
    expect(css).toContain('.session-list { padding-bottom: 0; }')
    expect(css).toContain('.session-dock { gap: 4px; padding-block: 4px calc(4px + env(safe-area-inset-bottom)); }')
    expect(css).not.toContain('.input-dock')
    expect(css).toContain('.request-stack > .permission-panel, .request-stack > .question-panel { border-bottom-color: var(--border); background: var(--surface); }')
  })

  it("keeps the overflow fade independent of hover/focus with a visible inset keyboard ring", () => {
    const css = source("../src/styles.css")
    const fade = css.match(/\.subagent-selector\[data-overflow-right="true"\]::after \{([^}]+)\}/)?.[1]
    expect(fade).toContain("pointer-events: none")
    expect(css).toMatch(/\.subagent-selector \{[^}]*width: 100%; max-width: 780px; margin-inline: auto;/)
    expect(fade).toContain("z-index: 1")
    expect(fade).toContain("top: calc(12px + env(safe-area-inset-top))")
    expect(fade).toContain("bottom: 0")
    expect(fade).toContain("width: 36px")
    expect(fade).toContain("background: linear-gradient(to right, transparent, var(--background))")
    expect(fade).toContain("mask-image: linear-gradient(to bottom, #000 calc(100% - 24px), transparent 100%)")
    expect(css).toContain("box-shadow: var(--elevation-floating)")
    expect(css).not.toMatch(/\.subagent-selector[^{}]*:(?:focus|hover)/)
    expect(css).toContain("scroll-margin-inline: 12px")
    expect(css).toContain('.subagent-list .subagent-pill:focus-visible::after { content: ""; position: absolute; z-index: 2; inset: 2px;')
    expect(css).toContain('--progress-border-color: var(--accent)')
    expect(css).toMatch(/@media \(prefers-reduced-motion: no-preference\) \{\s*\.pending-response i \{ animation: pending-response-pulse/)
  })

  it("shares the pill loading border and its reduced-motion fallback with the session header", () => {
    const css = source("../src/styles.css")
    const selector = '.session-header-pill[data-active="true"]::before, .subagent-pill:is([data-status="busy"], [data-status="retry"])::before, .session-avatar:is(.busy, .retry)::before, .tabs button[data-working="true"]::before'
    expect(css).toContain(`${selector} { content: ""; position: absolute;`)
    expect(css).toContain(`${selector} { animation: progress-border-travel 2.8s linear infinite; }`)
    expect(css).toContain(`@media (prefers-reduced-motion: reduce) {\n  ${selector} { background: var(--progress-border-color); }`)
  })

  it("keeps message text and timestamps above AA contrast in both themes with tighter prose and unchanged code leading", () => {
    const tokens = source("../public/design-tokens.css")
    const luminance = (hex: string) => hex.match(/\w\w/g)!.map((pair) => parseInt(pair, 16) / 255).map((c) => c <= .04045 ? c / 12.92 : ((c + .055) / 1.055) ** 2.4).reduce((sum, c, index) => sum + c * [ .2126, .7152, .0722 ][index]!, 0)
    for (const theme of ["dark", "light"]) {
      const block = tokens.split(`:root[data-theme="${theme}"] {`)[1]!.split("}")[0]!
      const token = (name: string) => block.match(new RegExp(`--message-own-${name}: (#\\w+);`))![1]!
      for (const foreground of ["text", "muted"]) expect((luminance(token("surface")) + .05) / (luminance(token(foreground)) + .05)).toBeGreaterThanOrEqual(4.5)
      expect(token("surface")).toBe(theme === "dark" ? "#efbc54" : "#f4d392")
    }
    const css = source("../src/styles.css")
    expect(css).toContain(".message p, .markdown ul, .markdown ol { font-size: 16px; line-height: 1.5; }")
    expect(css).toMatch(/\.markdown pre code \{[^}]*line-height: 1.6;/)
    expect(css).toContain(".session-avatar.needs-input { color: var(--info); background: var(--info-surface); }")
    expect(css).toContain(".command-bar .ui-button--danger { width: 44px; padding: 0; color: var(--danger); border-color: var(--danger); background: var(--danger-surface); }")
  })

  it("keeps progress draining bounded by a timeout", () => {
    const relay = source("../src/features/relay/hooks/useRelay.ts")
    expect(relay).toContain("Message progress timed out.")
    expect(relay).toContain("verifiedMessageIds")
  })

  it("uses exact, modal-only connection timing and preserves zero-millisecond RTT", () => {
    const connectionDetails = source("../src/features/workspace/ConnectionDetails.tsx")
    const relay = source("../src/features/relay/hooks/useRelay.ts")
    const connectionPresentation = source("../src/features/relay/connectionPresentation.ts")
    expect(connectionDetails).toContain("exactConnectionTime(relayState.lastSyncedAt, now)")
    expect(connectionDetails).toContain("relayConnectionPresentation(relayState.isRelayConnected(relay.id), health, now)")
    expect(connectionPresentation).toContain('health?.rtt !== undefined ? `${health.rtt} ms`')
    expect(connectionPresentation).toContain('health?.timedOut) return { state: "unstable", label: "Unstable", detail: health.lastContact ? `Last contact ${exactConnectionTime(health.lastContact, now)}` : "" }')
    expect(connectionDetails).toContain("window.setInterval(() => setNow(Date.now()), 1_000)")
    expect(relay).toContain("Connection handshake timed out.")
    expect(relay).toContain("HANDSHAKE_TIMEOUT_MS")
    expect(relay).toContain("shouldReconnectTransportOnResume")
    expect(relay).toContain("const retireTransport = useCallback")
    expect(relay).toContain('retireTransport("Connection interrupted")')
    expect(relay).toContain("pending.generation !== generation")
    expect(relay).toContain("setError((current) => current === \"Connection handshake timed out.\"")
    expect(relay).toContain("socket?.readyState === WebSocket.CONNECTING")
    expect(relay).toContain("shouldReconnectTransportOnResume")
  })

  it("uses effective status presentation for the header and unstable modal rows", () => {
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const connectionDetails = source("../src/features/workspace/ConnectionDetails.tsx")
    const css = source("../src/styles.css")
    expect(workspace).toContain("const connectionPresentation = effectiveConnectionPresentation(relayState.connection, connectedRelayIds, relayState.relays.length, relayState.relayHealth)")
    expect(workspace).toContain("connection-state ${connectionPresentation.tone}")
    expect(workspace).toContain('connectionPresentation.state === "online" ? <Wifi size={15} /> : <WifiOff size={15} />')
    expect(connectionDetails).toContain("const service = serviceConnectionPresentation(relayState.serviceConnected, overall)")
    expect(connectionDetails).toContain("connection-workspace ${presentation.state}")
    expect(css).toContain(".connection-row.unstable b, .connection-row.unstable b small { color: var(--amber); }")
  })

  it("binds selected cache callbacks to the stable workspace ID and persists directly through the keyed store queue", () => {
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    expect(workspace).toContain("relayState.loadCache<T>(selected.workspaceId, resource, selected.id)")
    expect(workspace).toContain("relayState.saveCache(selected.workspaceId, resource, value, selected.id)")
    expect(workspace).not.toContain("relayState.loadCache<T>(selected.workspaceRelayId, resource, selected.id)")
    expect(workspace).not.toContain("relayState.saveCache(selected.workspaceRelayId, resource, value, selected.id)")
    expect(sessionDetail).not.toContain("persistenceRef")
    expect(sessionDetail).toContain("return saveCache(\"messages\", cache).then(() => {")
    expect(sessionDetail).toContain("formatMessageCacheSaveFailure(cause)")
    expect(sessionDetail).toContain("shouldReportCacheFailure(lastPersistenceFailureRef.current, message, now)")
    expect(sessionDetail).toContain("shouldReportCacheFailure(lastTodoPersistenceFailureRef.current, message, now)")
    expect(sessionDetail).toContain("if (!outcome.messages) return")
    expect((sessionDetail.match(/void persistLocalMessages\(next\)\.catch\(\(\) => undefined\)/g) ?? [])).toHaveLength(3)
    expect(sessionDetail).toContain("const persistTodosCache = useCallback((todos: SessionTodo[]) => {")
    expect(sessionDetail).toContain("void saveCache(\"todos\", todos).then(() => {")
    expect(sessionDetail).toContain("if (key === \"todos\") persistTodosCache(next as SessionTodo[])")
    expect(sessionDetail).toContain("Could not load local todos cache: ${messageCacheErrorDetail(error)}")
    expect(sessionDetail).toContain("loadCache<SessionTodo[]>(\"todos\").then((cached)")
    expect(sessionDetail).toContain(".catch((error) => {\n        if (generation !== generationRef.current) return\n        onError(`Could not load local todos cache:")
    expect(sessionDetail).toContain("]).then(() => { if (generation === generationRef.current) setLoading(false) })")
    const relay = source("../src/features/relay/hooks/useRelay.ts")
    expect(relay).toContain("void saveCachedResource(identity, stableWorkspaceKey(data.relay), \"snapshot\", {")
    expect(relay).toContain("}).then(() => {\n          snapshotCacheFailureRef.current = undefined\n        }).catch((cause) => {")
    expect(relay).toContain("shouldReportCacheFailure(snapshotCacheFailureRef.current, message, now)")
    expect(relay).toContain("Workspace state is current, but local cache could not be saved:")
  })

  it("keeps an already-stable cache namespace after the transient relay slice disappears", () => {
    expect(cacheNamespace("workspace-stable")).toBe("workspace-stable")
    expect(cacheNamespace("transient-relay", { workspaceId: "workspace-stable", hostname: "host", workspace: "/repo" })).toBe("workspace-stable")
  })
})
