import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"
import { cacheNamespace } from "../src/features/relay/useRelay"

const source = (path: string) => readFileSync(new URL(path, import.meta.url), "utf8")

describe("layout source contracts", () => {
  it("keeps connection details scrollable with fixed dialog chrome", () => {
    const css = source("../src/styles.css")
    const workspace = source("../src/pages/WorkspacePage.tsx")
    expect(css).toContain("max-height: calc(100dvh - 36px)")
    expect(css).toContain(".connection-dialog-body { min-height: 0; overflow-y: auto; }")
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto")
    expect(workspace).toContain('className="connection-dialog-body"')
  })

  it("keeps tabs mobile-scrollable and exposes the subagent tab contract", () => {
    const css = source("../src/styles.css")
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    expect(css).toContain(".tabs { height: 46px; flex: 0 0 auto; display: flex; gap: 6px; overflow-x: auto")
    expect(sessionDetail).toContain("const visibleSubagentEntries = useMemo(() => visibleSubagents(subagents), [subagents])")
    expect(sessionDetail).toContain("Subagents <span>{visibleSubagentEntries.length}</span>")
    expect(sessionDetail).toContain("<SubagentActivity subagents={visibleSubagentEntries}")
    expect(workspace).toContain("if (group) group.push(session)")
    expect(sessionDetail).toContain("messageRefreshGenerationRef")
    expect(sessionDetail).toContain("todosRefreshGenerationRef")
    expect(sessionDetail).toContain("const selectTab")
    expect(sessionDetail).toContain("followOutputRef.current = true")
    expect(sessionDetail).toContain("lastScrollTopRef.current = detailContentRef.current.scrollTop")
    expect((sessionDetail.match(/lastScrollTopRef\.current = detailContentRef\.current\.scrollTop/g) ?? [])).toHaveLength(2)
  })

  it("hides the composer and root working strip for subagent activity while restoring output follow on Activity", () => {
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    expect(sessionDetail).toContain('const showComposer = tab !== "subagents"')
    expect(sessionDetail).toContain("{showComposer && (session.status === \"busy\" || session.status === \"retry\")")
    expect(sessionDetail).toContain('{showComposer && <form className="composer" onSubmit={submit}>')
    expect(sessionDetail).toContain('if (next === "activity")')
    expect(sessionDetail).toContain("detailContentRef.current.scrollTop = detailContentRef.current.scrollHeight")
    expect(sessionDetail).not.toContain("document.activeElement === promptRef.current")
    expect(sessionDetail).toContain("followOutputRef.current = true\n          const prepared = await prepareMessageProgress(partial)\n          if (!owns() || !isRequestActive()) return\n          const cache = applyPreparedMessageProgress(messageCacheRef.current, prepared)")
    expect(sessionDetail).toContain("const cache = applyPreparedMessageProgress(messageCacheRef.current, prepared)\n          await persistMessageCache(cache)")
    expect(sessionDetail).toContain("lastScrollTopRef.current = detailContentRef.current.scrollTop")
  })

  it("keeps Subagents scrolling within its fixed-height detail region", () => {
    const css = source("../src/styles.css")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    const subagents = source("../src/features/session/components/SubagentActivity.tsx")
    expect(sessionDetail).toContain('className={`detail-content ${tab === "subagents" ? "subagent-content" : ""}`}')
    expect(sessionDetail).toContain('className={`input-dock ${tab === "subagents" ? "subagent-dock" : ""}`}')
    expect(subagents).toContain('className="subagent-messages"')
    expect(subagents).toContain('className="subagent-message-scroll" ref={messageScrollRef}')
    expect(subagents).toContain('const messageScrollRef = useRef<HTMLDivElement>(null)')
    expect(subagents).toContain('scroll.scrollTop = scroll.scrollHeight')
    expect(subagents).toContain('}, [childKey, messages, loading, error, workLabel])')
    expect(css).toContain(".detail-header { min-height: 86px; flex: 0 0 auto;")
    expect(css).toContain(".tabs { height: 46px; flex: 0 0 auto;")
    expect(css).toContain(".detail-content.subagent-content { min-height: 0; overflow: hidden; }")
    expect(css).toContain(".input-dock.subagent-dock { min-height: 0; max-height: min(52dvh, max(0px, calc(100dvh - 64px - env(safe-area-inset-top) - 86px - 46px - 160px))); overflow-x: hidden; overflow-y: auto; overscroll-behavior: contain; }")
    expect(css).toContain(".input-dock.subagent-dock { max-height: min(52dvh, max(0px, calc(100dvh - 56px - env(safe-area-inset-top) - 76px - 46px - 132px - 112px))); }")
    expect(css).toContain(".subagent-dock .permission-panel, .subagent-dock .question-panel { max-height: none; }")
    expect(css).toContain(".subagent-dock .permission-panel, .subagent-dock .question-panel:not(.collapsed) { overflow: visible; }")
    expect(css).toContain(".subagent-view { height: 100%; min-height: 0; display: grid; grid-template-columns: minmax(190px, 280px) minmax(0, 1fr); grid-template-rows: minmax(0, 1fr); }")
    expect(css).toContain(".subagent-list { min-height: 0; overflow-y: auto; }")
    expect(css).toContain(".subagent-messages { min-height: 0; display: flex; flex-direction: column; overflow: hidden; }")
    expect(css).toContain(".subagent-messages > .work-strip { flex: 0 0 auto; }")
    expect(css).toContain(".subagent-message-scroll { min-height: 0; flex: 1 1 auto; overflow-y: auto;")
    expect(css).toContain(".subagent-message-scroll > .message-list { width: 100%; min-width: 0; overflow: visible; }")
    expect(css).toContain("@media (max-width: 640px) { .subagent-view { grid-template-columns: 1fr; grid-template-rows: auto minmax(0, 1fr); }")
    expect(css).toContain(".subagent-list { max-height: 132px; border-right: 0; border-bottom: 1px solid var(--line); }")
  })

  it("keeps progress draining bounded by a timeout", () => {
    const relay = source("../src/features/relay/useRelay.ts")
    expect(relay).toContain("Message progress timed out.")
    expect(relay).toContain("verifiedMessageIds")
  })

  it("uses exact, modal-only connection timing and preserves zero-millisecond RTT", () => {
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const relay = source("../src/features/relay/useRelay.ts")
    const connectionPresentation = source("../src/features/relay/connectionPresentation.ts")
    expect(workspace).toContain("exactConnectionTime(relayState.lastSyncedAt, now)")
    expect(workspace).toContain("relayConnectionPresentation(relayState.isRelayConnected(relay.id), health, now)")
    expect(connectionPresentation).toContain('health?.rtt !== undefined ? `${health.rtt} ms`')
    expect(connectionPresentation).toContain('health?.timedOut) return { state: "unstable", label: "Unstable", detail: health.lastContact ? `Last contact ${exactConnectionTime(health.lastContact, now)}` : "" }')
    expect(workspace).toContain("window.setInterval(() => setNow(Date.now()), 1_000)")
    expect(relay).toContain("Connection handshake timed out.")
    expect(relay).toContain("HANDSHAKE_TIMEOUT_MS")
    expect(relay).toContain("shouldReconnectTransportOnResume")
    expect(relay).toContain("const retireTransport = useCallback")
    expect(relay).toContain('retireTransport("Connection interrupted")')
    expect(relay).toContain("pending.generation !== generation")
    expect(relay).toContain("setError((current) => current === \"Connection handshake timed out.\"")
    expect(relay).toContain("socket?.readyState === WebSocket.CONNECTING")
    expect(relay).toContain("shouldReconnectTransportOnResume")
  })

  it("uses effective status presentation for the header and unstable modal rows", () => {
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const css = source("../src/styles.css")
    expect(workspace).toContain("const connectionPresentation = effectiveConnectionPresentation(relayState.connection, connectedRelayIds, relayState.relays.length, relayState.relayHealth)")
    expect(workspace).toContain("connection-state ${connectionPresentation.tone}")
    expect(workspace).toContain('connectionPresentation.state === "online" ? <Wifi size={15} /> : <WifiOff size={15} />')
    expect(workspace).toContain("const service = serviceConnectionPresentation(relayState.serviceConnected, overall)")
    expect(workspace).toContain("connection-row ${presentation.state}")
    expect(css).toContain(".connection-row.unstable b, .connection-row.unstable b small { color: var(--amber); }")
  })

  it("binds selected cache callbacks to the stable workspace ID and persists directly through the keyed store queue", () => {
    const workspace = source("../src/pages/WorkspacePage.tsx")
    const sessionDetail = source("../src/features/session/components/SessionDetail.tsx")
    expect(workspace).toContain("relayState.loadCache<T>(selected.workspaceId, resource, selected.id)")
    expect(workspace).toContain("relayState.saveCache(selected.workspaceId, resource, value, selected.id)")
    expect(workspace).not.toContain("relayState.loadCache<T>(selected.workspaceRelayId, resource, selected.id)")
    expect(workspace).not.toContain("relayState.saveCache(selected.workspaceRelayId, resource, value, selected.id)")
    expect(sessionDetail).not.toContain("persistenceRef")
    expect(sessionDetail).toContain("return saveCache(\"messages\", cache).then(() => {")
    expect(sessionDetail).toContain("formatMessageCacheSaveFailure(cause)")
    expect(sessionDetail).toContain("shouldReportCacheFailure(lastPersistenceFailureRef.current, message, now)")
    expect(sessionDetail).toContain("shouldReportCacheFailure(lastTodoPersistenceFailureRef.current, message, now)")
    expect(sessionDetail).toContain("if (!outcome.messages) return")
    expect((sessionDetail.match(/void persistLocalMessages\(next\)\.catch\(\(\) => undefined\)/g) ?? [])).toHaveLength(3)
    expect(sessionDetail).toContain("const persistTodosCache = useCallback((todos: SessionTodo[]) => {")
    expect(sessionDetail).toContain("void saveCache(\"todos\", todos).then(() => {")
    expect(sessionDetail).toContain("if (key === \"todos\") persistTodosCache(next as SessionTodo[])")
    expect(sessionDetail).toContain("Could not load local todos cache: ${messageCacheErrorDetail(error)}")
    expect(sessionDetail).toContain("loadCache<SessionTodo[]>(\"todos\").then((cached)")
    expect(sessionDetail).toContain(".catch((error) => {\n        if (generation !== generationRef.current) return\n        onError(`Could not load local todos cache:")
    expect(sessionDetail).toContain("]).then(() => { if (generation === generationRef.current) setLoading(false) })")
    const relay = source("../src/features/relay/useRelay.ts")
    expect(relay).toContain("void saveCachedResource(identity, stableWorkspaceKey(data.relay), \"snapshot\", {")
    expect(relay).toContain("}).then(() => {\n          snapshotCacheFailureRef.current = undefined\n        }).catch((cause) => {")
    expect(relay).toContain("shouldReportCacheFailure(snapshotCacheFailureRef.current, message, now)")
    expect(relay).toContain("Workspace state is current, but local cache could not be saved:")
  })

  it("keeps an already-stable cache namespace after the transient relay slice disappears", () => {
    expect(cacheNamespace("workspace-stable")).toBe("workspace-stable")
    expect(cacheNamespace("transient-relay", { workspaceId: "workspace-stable", hostname: "host", workspace: "/repo" })).toBe("workspace-stable")
  })
})
